# Generated by Django 4.1.1 on 2022-10-16 08:31

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('todo_completed', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'todolist',
                'verbose_name_plural': 'todolists',
                'db_table': 'todolists',
            },
        ),
    ]
